### ISSUE TITLE
remove the header & footer (more minimal)

### ISSUE THREAD

**Issue by greenify** [AgonLohaj/hssp_curve#5]
Hi,

it would be great if you could remove the header and footer from your component or at least make this optional. It is better to put the explanation etc. in the `README.md` (=documentation file)

Reason: If someone wants to embed your component, he is most likely only interested in the filtering functionality and the graph itself.

**Comment by bardhlohaj** [comment]
We removed the footer and we made the title and description as optional(false by default).
